version: '3.9'

services:
  grpc_proj:
    build: ./
    command: ./grpc_proj
    ports:
      - 8000:8000
    depends_on:
      - db
      - clickhouse
      - zookeeper
      - kafka
      - redis

  db:
    restart: always
    image: postgres:latest
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=21052002
    - POSTGRES_DB=clientbase
    - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
      - .:/docker-entrypoint-initdb.d
    ports:
      - 5436:5432

  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - 9000:9000
    volumes:
      - ./.database/clickhouse/data:/var/lib/clickhouse

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181

  redis:
    image: redis:alpine
    volumes:
      - ./.database/clickhouse/data:/data
    ports:
      - 6379:6379

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
