version: '3.9'

services:
  grpc_proj:
    build: ./
    command: ./grpc_proj
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    restart: always
    image: postgres:latest
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=21052002
    - POSTGRES_DB=clientbase
    - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
      - .:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
