db:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "21052002"
  dbname: "clientbase"
  sslmode: "disable"
  drivername: "postgres"

additional_db:
  drivername: "clickhouse"

app:
  addressforlisten: "127.0.0.1:8000"
