db:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "21052002"
  dbname: "clientbase"
  sslmode: "disable"
  drivername: "postgres"

additional_db:
  drivername: "clickhouse"
  dsn: "tcp://127.0.0.1:9000?debug=true"

app:
  addressforlisten: "127.0.0.1:8000"

logger:
  drivername: "kafka"
  dsn: "localhost:9092"
  host: "localhost"

cache:
  drivername: "redis"
  dsn: "127.0.0.1:6379"
